Provide a few global console commands by default
yasirkula/UnityIngameDebugConsole pull request #54
Opened 2021-04-07 15:18 UTC by tonygiang

I use the Command Console feature extensively for work projects. Among the commands I have written, I identified a few commands that are universally helpful to the purpose of runtime testing no matter which project I use this package for. It makes sense to me that these universally-helpful commands should be shipped by default. This can be the beginning of more than just `help` and `sysinfo` being shipped by default with In-game Debug Console (IGDC). The command groups I created are:

`PlayerPrefsCommands`: There is actually no readily-available tool to read and modify PlayerPrefs in-game for Unity. So I thought: with very minimal code addition, IGDC could just fill that gap. The 4 commands are `pp.get`, `pp.set`, `pp.delete`, `pp.clear`.

`TimeCommands`: Just 2 commands to set the game's time scale value and to read the current time scale. They are `time.scale` and `time.currentscale`. I use this to manipulate time during debug session without creating an extra button on the UI for each scene context.

`SceneCommands`: Just 2 commands to load and unload scenes. They are `scene.load` and `scene.unload`. `scene.load` accepts a load mode parameter too.

Because IGDC is particularly useful for mobile test environment where typing is really a chore, I tried to make command names short and parameters as case-insensitive as possible. We can update the documentation to reflect the new commands later, but fortunately, `help` command already listed all commands by default.

2021-04-09 12:18 UTC, yasirkula requested changes
Thank you for the PR! Please take a look at the suggested changes.

2021-04-09 12:18 UTC, yasirkula commented on Plugins/IngameDebugConsole/Scripts/Commands/PlayerPrefsCommands.cs
> +		[ConsoleMethod( "pp.del", "Delete a PlayerPrefs field", "key" )]
**prefs.delete** would be more preferable

2021-04-09 12:18 UTC, yasirkula commented on Plugins/IngameDebugConsole/Scripts/Commands/PlayerPrefsCommands.cs
> +			"Get the value of a PlayerPrefs field",
Please use present tense to be consistent with _help_ and _sysinfo_. Instead of _Get_, prefer _Returns_

2021-04-09 13:23 UTC, tonygiang commented
I didn't know about command overloading, good to know. I'm incorporating your requested changes, but I do have one concern about picking async/sync mode for scene unload: `SceneManager.UnloadScene` has been obsoleted by Unity with the following warning message: `Use SceneManager.UnloadSceneAsync. This function is not safe to use during triggers and under other circumstances. See Scripting reference for more details.`

Are you sure you still want a sync mode for scene unload moving forward?

2021-04-09 13:25 UTC, yasirkula commented
Didn't know about that. We don't need UnloadScene in that case.

2021-04-09 13:41 UTC, tonygiang commented
The requested changes are live for review.

2021-04-10 14:43 UTC, yasirkula commented
Thank you for the changes!

2021-04-10 14:44 UTC, merged